version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: Asia/Tokyo
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle install --path=vendor/bundle && bundle exec rails server -b 0.0.0.0
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./api:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    ports:
      - 3000:3000
    depends_on:
      - db

  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app
    command: sh -c "yarn start"
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8000:3000
    depends_on:
      - api
volumes:
    db-data:
    public-data:
    tmp-data:
    log-data:
