version: 2.1

jobs:
  test_api:
    docker:
      - image: circleci/ruby:3.0.2
        environment:
          RAILS_ENV: test
          host: db
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    working_directory: ~/template-app

    steps:
      - checkout

      # Database setup
      - run:
          command: bundle exec rails db:create
          working_directory: ~/template-app/api
      - run:
          command: bundle exec rails db:migrate
          working_directory: ~/template-app/api
      - run:
          name: create directory to store test results
          command: mkdir /tmp/test-results
          working_directory: ~/template-app/api

      # restore gem from cache
      #- restore_cache:
      #    keys:
      #      - gem-cache-v1-{{ checksum "~/api/Gemfile.lock" }}
      #      - gem-cache-v1-
      #    working_directory: ~/template-app/api

      # gem install
      - run:
          command: |
            gem install bundler
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
          working_directory: ~/template-app/api

      - save_cache:
          key: gem-cache-v1-{{ checksum "~/template-app/api/Gemfile.lock" }}
          paths:
            - api/vendor/bundle
          working_directory: ~/template-app/api

      # run tests
      - run:
          name: RSpec
          command: |
            bundle exec rspec $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings) \
              || (printf "====== RETRYING...\n\n\n"; bundle exec rspec --only-failures)
          working_directory: ~/template-app/api

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  test_front:
    docker:
      - image: circleci/node:14.15.4-alpine
        environment:
          NODE_ENV: test

    working_directory: ~/template-app

    steps:
      - checkout
    #  - restore_cache:
    #      keys:
    #        - v1-dependencies-{{ checksum "~/template-app/front/package.json" }}
    #      working_directory: ~/template-app/front
      - run:
          name: install-packages
          command: npm install
          working_directory: ~/template-app/front
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "~/template-app/front/package.json" }}
          working_directory: ~/template-app/front
      - run:
          name: test
          command: npm run test
          working_directory: ~/template-app/front

workflows:
  version: 2
  test:
    jobs:
      - test_api:
          filters:
            branches:
              ignore: main
      - test_front:
          filters:
            branches:
              ignore: main