FROM ruby:3.0

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

RUN mkdir /myapp
WORKDIR /myapp

COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock

RUN apt-get update -qq && \
    apt-get install -y build-essential \
    libpq-dev \
    vim \
    curl \
    imagemagick &&\
    gem install bundler:2.2.22

RUN bundle install

COPY . /myapp
# RUN mkdir -p tmp/sockets
# RUN mkdir tmp/pids

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 80

# コマンドを実行
CMD ["bundle", "exec", "rails", "s", "-b", "0.0.0.0", "-p", "80", "-e", "production"]
